### ISSUE TITLE
Can't install for basilisk browser

### ISSUE THREAD

**Issue by phungvuong** [sheddup/YoutubeAUDIO#10]
Working on firefox but i can't install it to basilisk browser. Can you help.

**Comment by sheddup** [comment]
I'll look into it

**Comment by sheddup** [comment]
YoutubeAUDIO is a WebExtension add-on which Basilisk does not support.
Basilisk supports classic Firefox add-ons which you can install from here - https://addons.basilisk-browser.org/ or the classic add-ons archive - https://github.com/JustOff/ca-archive

Any WebExtension type add-on you try to install will fail with the error "could not be installed because Basilisk does not support WebExtensions"

![Untitled](https://user-images.githubusercontent.com/5480335/85290377-6918b400-b488-11ea-9e1d-7d8fc887f2a3.png)

**Comment by sheddup** [comment]
As far as listening to youtube in audio only, the website Invidious lets you listen to and also watch youtube videos https://invidio.us/watch?v=xY96v0OIcK4 click the headphone icon next to the video title to listen to the video

**Comment by sheddup** [comment]
I would say you can use https://invidio.us to listen to Youtube but Basilisk doesn't appear to work with the audio only feature
